default_index:
  path: /
  defaults: { _controller: "AppBundle:Default:index" }
  methods: GET

default_pruebas:
  path: /pruebas
  defaults: { _controller: "AppBundle:Default:pruebas" }
  methods: GET

default_login:
  path: /login
  defaults: { _controller: "AppBundle:Default:login" }
  methods: POST

default_logintest:
  path: /logintest/{rut}/{clave}
  defaults: { _controller: "AppBundle:Default:logintest" }
  methods: GET