BackendBundle\Entity\Testime:
    type: entity
    table: testime
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: date
            nullable: true
        hora:
            type: time
            nullable: true
    lifecycleCallbacks: {  }
