BackendBundle\Entity\TipoRiego:
    type: entity
    table: tipo_riego
    id:
        tipoId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: tipo_id
            generator:
                strategy: IDENTITY
    fields:
        tipoDescripcion:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: tipo_descripcion
        eliminarEstado:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: eliminar_estado
    lifecycleCallbacks: {  }
